planning_plugin: ompl_interface/OMPLPlanner

request_adapters: >-
  default_planning_request_adapters/ResolveConstraintFrames
  default_planning_request_adapters/ValidateWorkspaceBounds
  default_planning_request_adapters/CheckStartStateBounds

response_adapters: >-
  default_planning_response_adapters/AddTimeOptimalParameterization
  default_planning_response_adapters/DisplayMotionPath

ur5_arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault

planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.2
